// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGrpZayh_lnl23i5hJcC0CvoPFyoD90os',
    appId: '1:778394648288:web:a5f8626f46aacdc5709a85',
    messagingSenderId: '778394648288',
    projectId: 'cubicle-fitness',
    authDomain: 'cubicle-fitness.firebaseapp.com',
    storageBucket: 'cubicle-fitness.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgaQ1o0S2lYAvUdfC-vDudV5b2UUtxm80',
    appId: '1:778394648288:android:ea7ff95ea6f436e5709a85',
    messagingSenderId: '778394648288',
    projectId: 'cubicle-fitness',
    storageBucket: 'cubicle-fitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBysxtjIW85on4GUsh88uo3qwf5MF6_O8k',
    appId: '1:778394648288:ios:423debfc91b539eb709a85',
    messagingSenderId: '778394648288',
    projectId: 'cubicle-fitness',
    storageBucket: 'cubicle-fitness.appspot.com',
    iosBundleId: 'com.sebastianmattsson.cubicleFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBysxtjIW85on4GUsh88uo3qwf5MF6_O8k',
    appId: '1:778394648288:ios:8476fc37c5f7f12b709a85',
    messagingSenderId: '778394648288',
    projectId: 'cubicle-fitness',
    storageBucket: 'cubicle-fitness.appspot.com',
    iosBundleId: 'com.example.cubicleFitness.RunnerTests',
  );
}
